FROM node:20-alpine

WORKDIR /app

ENV NODE_ENV=production

COPY frontend/package.json frontend/package-lock.json /app/
RUN npm ci

COPY frontend /app
RUN npm run build

EXPOSE 3000

CMD ["npm", "run", "start"]
